### ISSUE TITLE
Создаёт только префикс пароля

### ISSUE THREAD

**Issue by G-L-X-B** [rkolovanov/password-generator#1]
Пытаюсь создать пароль, ввожу префикс, но ничего, кроме префикса, в строке пароля не появляется. При нажатии на кнопку копируется только префикс.

**Comment by G-L-X-B** [comment]
![Screenshot_20220228_224609](https://user-images.githubusercontent.com/24878176/156048602-3090a655-86f3-40b1-9deb-2b98dd73c8ed.png)

**Comment by rkolovanov** [comment]
Пока вторая часть пароля вводиться вручную в [этой строке](https://github.com/rkolovanov/password-generator/blob/0b99a80ed95811cd21a7c7be4cc9c09343667689/gui/MainWindow.py#L18). В дальнейшем будет предусмотрен конфигурационный файл для настройки.

**Comment by rkolovanov** [comment]
Возможно еще подумаю над дополнительным функционалом генерации паролей, на скрине еще заметил багич, что пробелы не удаляются (надо будет их пробелы заменить).

**Comment by CmmSheparD** [comment]
Думаю, случайная генерация предпочтительней, чем строки в коде.

**Comment by G-L-X-B** [comment]
Всё ещё не генерирует (
